kind: Service
apiVersion: v1
metadata:
  name: prom-pod
  labels: 
    app: prom-pod
spec:
  ports:
    - port: 9090
      targetPort: loc-prom-web
      protocol: TCP
  selector:
    app: prom-pod
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-pod
  template:
    metadata:
      labels:
        app: prom-pod
    spec:
      containers:
        - name: prom-pod
          image: prom/prometheus:v2.19.1
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - name: loc-prom-web
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prom-conf
  
        - name: prometheus-storage-volume
          emptyDir: {}

