---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-conf
  labels:
    name: cloudwatch-conf
data:
  config.yml: |-
    region: {{aws_region}}
    metrics:
      - aws_namespace: AWS/ELB
        aws_metric_name: RequestCount
        aws_dimensions: [AvailabilityZone, LoadBalancerName]
        aws_dimension_select:
          LoadBalancerName: [{{elb_name}}]
        aws_statistics: [Sum]
      - aws_namespace: AWS/RDS
        aws_metric_name: CPUUtilization
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select:
          DBInstanceIdentifier: [{{db_identifier}}]
        aws_statistics: [Sum]
      - aws_namespace: AWS/RDS
        aws_metric_name: ReadIOPS
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select:
          DBInstanceIdentifier: [{{db_identifier}}]
        aws_statistics: [Sum]
      - aws_namespace: AWS/RDS
        aws_metric_name: WriteIOPS
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select:
          DBInstanceIdentifier: [{{db_identifier}}]
        aws_statistics: [Sum]
